#!/bin/bash

TOOLCHAIN_DIR=$(head -n 1 /etc/kos32-gcc/install-path)

MESSAGE="PATH=\$PATH:$TOOLCHAIN_DIR"

if  grep -q $MESSAGE /etc/profile; then
	sed -i '/$MESSAGE/d' /etc/profile
fi

rm /etc/kos32-gcc -R

