name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  #Test linux install script
  linux-install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run script
        run: echo '/home/autobuild/tools' | ${{ github.workspace }}/./install.sh

      - name: Add toolchain to path
        run: echo "/home/autobuild/tools/win32/bin" >> $GITHUB_PATH

      - name: Test run
        run: |
          kos32-gcc -v
          kos32-g++ -v

  #Test windows install script
  windows-install:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install depends
        run: |
         choco install wget
         choco install 7zip

      - name: Run script
        run: ${{ github.workspace }}/install.bat

  #Test Windows Installer
  build-Installer:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cmake -B ${{ github.workspace }}/build
          cmake --build ${{ github.workspace }}/build --target Installer

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          # Upload entire repository
          path: './build/installer.exe'

  # Test Package
  deb-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
              
      - name: Build
        run: |
          cmake -B ${{ github.workspace }}/build
          cmake --build ${{ github.workspace }}/build --target Package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          # Upload entire repository
          path: './build/package.deb'
        
      - name: Install package
        run: echo '/kolibrios-toolchain' | sudo apt install ${{ github.workspace }}/build/package.deb -y
        
      - name: Add toolchain to path
        run: echo "/kolibrios-toolchain/win32/bin" >> $GITHUB_PATH
        
      - name: Test run
        run: |
          kos32-g++ -v
          kos32-gcc -v
          /home/autobuild/tools/win32/bin/kos32-gcc -v
          /home/autobuild/tools/win32/bin/kos32-g++ -v
          /kolibrios-toolchain/win32/bin/kos32-gcc -v
          /kolibrios-toolchain/win32/bin/kos32-g++ -v

      - name: Remove package
        run: sudo apt remove kos32-gcc

  #Test chocolatey package
  chocolatey-package:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cmake -B ${{ github.workspace }}/build
          cmake --build ${{ github.workspace }}/build --target 

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: choco-package
          # Upload entire repository
          path: './build/'
