name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  linux-install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run script
        run: ${{ github.workspace }}/./install.sh

      - name: Add toolchain to path
        run: echo "/home/autobuild/tools/win32/bin" >> $GITHUB_PATH

      - name: Test run
        run: |
          kos32-gcc -v
          kos32-g++ -v

  windows-install:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install depends
        run: |
         choco install wget
         choco install 7zip

      - name: Run script
        run: ${{ github.workspace }}/install.bat

      - name: Add toolchain to path
        run: echo "C:\MinGW\msys\1.0\home\autobuild\tools\win32\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Test run
        run: |
          kos32-g++ -v
          kos32-gcc -v
        shell: cmd

  build-Installer:
    runs-on: windowd-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cmake -B ${{ github.workspace }}/build
          cmake --build ${{ github.workspace }}/build --target Installer

  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
              
      - name: Build
        run: |
          cmake -B ${{ github.workspace }}/build
          cmake --build ${{ github.workspace }}/build --target Package
        
      - name: Install package
        run: sudo dpkg -i ${{ github.workspace }}/package.deb
        
      - name: Add toolchain to path
        run: echo "/home/autobuild/tools/win32/bin" >> $GITHUB_PATH
        
